language: java

env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2

jdk:
  - openjdk8

before_script:
  - cd "EnchantmentTokensMain/EnchantmentTokensPublic"
  - ./gradlew build test publishToMavenLocal

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
