language: java

env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2

jdk:
  - openjdk8

jobs:
  include:
    - name: EnchantmentTokensAPI
      language: java
      os: linux
      before_install:
        cd EnchantmentTokensMain/EnchantmentTokensPublic
      script:
        ./gradlew shadowJar test
    - name: EnchantmentTokens
      language: java
      os: linux
      script:
        ./gradlew check
        ./gradlew codeCoverageReport
      after_success:
        bash <(curl -s https://codecov.io/bash)
