name: EnchantmentTokens
description: Add some custom enchantments to your world!
author: Big_Bad_E
version: 1.1
api-version: 1.13
main: software.bigbade.enchantmenttokens.EnchantmentTokens
depend: [ProtocolLib]
softdepend:
  - Vault
  - Skript
commands:
  adminenchant:
    description: Enchant an item. (Admin only)
    usage: /adminenchant (enchant) (level)
  tokenenchant:
    description: Enchant an item using gems.
    usage: /customenchant
    aliases: [customenchants, tokenenchant, tokenenchants, ce, te, et, enchanttoken, enchanttokens]
  gembalance:
    description: Get your current gem balance.
    usage: /gembalance
    aliases: [gembal, gbal, gems]
  addgems:
    description: Add gems to a player's balance
    usage: /addgems [player] (amount)
  reloadenchants:
    description: Reload all enchants in the jar
    usage: /reloadenchants
  enchantlist:
    description: Lists all current enchants
    usage: /enchantlist
  paygems:
    description: Pay gems to another player
    usage: /paygems (player) (amount)
    aliases: [paytokens, paygem, paytoken]
permissions:
  enchanttoken.admin:
    description: Allows for admins to enchant an item.
    default: false
  enchanttoken.list:
    description: Allows users to view enchantments
    default: true